import React, { useState, useEffect } from 'react';
import Head from 'next/head'; // Next.jsのHeadコンポーネントをインポート



const HomePage: React.FC = (props) => {

  return (
    <div>
      <Head>
        <title>My Next.js Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Hello</h1>
        <p>
          Get started by editing{' '}
          <code>pages/index.tsx</code>
        </p>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
        </a>
      </footer>
    </div>
  );
};

export default HomePage;